[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix_macro = { path = "matrix_macro" }
ocl = { version = "0.19.0", git = "https://github.com/forkaduck/ocl" }
log = "0.4.21"
simplelog = "0.12.2"

[dev-dependencies]
oorandom = "11.1.3"
