[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix_macro = { path = "matrix_macro" }
ocl = "0.19.0"
log = "0.4.21"
simple_logger = { version = "5.0.0", features = ["colors"] }

[dev-dependencies]
rand = "0.8.5"
